### ISSUE TITLE
Extension returns error - KeyError: 'show_checks'

### ISSUE THREAD

**Issue by bobmacks** [mediro-ict/activegate_python_ssl_plugin#3]
Hi,

Our Activegate installed is `Version 1.207.228.20210114-161145`

Remote Plugin details from logs:
```
Version ..................... 1.207.232.20210118-113208, build date 2021.01.18 11:32:08, SCM Rev. 66f2e3e224bffac4eb6061bbcb5d09718b479a50
Command line is oneagentremoteplugin -Dcom.compuware.apm.WatchDogPort=50001 -Dcom.compuware.apm.WatchDogTimeout=900 
Build platform .............. Linux x86 64-bit
Platform .................... Linux - Amazon Linux 2 4.14.203-156.332.amzn2.x86_64 x86_64
System startup time ......... 2020-12-30 22:14:28 UTC
Local timezone .............. UTC+0000
User name ................... dynatrace
Bootstrap version ........... 1.207.232.20210118-113208
Log level console ........... none
Log level file .............. info
Log file .................... /var/lib/dynatrace/remotepluginmodule/log/remoteplugin/ruxitagent_remotepluginagent_26548.0.log
APR version ................. 1.6.5
cURL version ................ libcurl/7.72.0 OpenSSL/1.1.1i zlib/1.2.11
OpenSSL version ............. OpenSSL 1.1.1i  8 Dec 2020
zlib version ................ 1.2.11
Snappy version .............. 1.1.8
Zstandard version ........... 1.4.5
Installer version ........... 1.207.233.20210118-133635
```

After installing the SSL Checker remote plugin into our Environment Activegate and setting up the custom extension to Dynatrace SaaS, we received the error `Error(show_checks)`.

From the Activegate remote plugin logs we get the following error. 

```
2021-03-02 22:12:43.461 UTC [e75f9898] info    [native] 140294693578496(MainThread) - [trigger_plugins_life] active plugins changed
2021-03-02 22:12:43.461 UTC [e6bfa898] info    [native] 140294683088640(ThreadPoolExecutor-0_0) - [event_set_configuration] event_set_configuration, plugin: <RemotePluginEngine, meta_name:custom.remote.python.ssl_events id:0x7f990854ea20> config: {'poll_interval': 900, 'period': 61, 'event_type': 'Custom Info', 'hosts': 'www.google.com:443', 'alert_period': 7}
2021-03-02 22:12:43.542 UTC [e6bfa898] info    [native] 140294683088640(ThreadPoolExecutor-0_0) - [initialize] Config: {'poll_interval': 900, 'period': 61, 'event_type': 'Custom Info', 'hosts': 'www.google.com:443', 'alert_period': 7}
2021-03-02 22:12:43.543 UTC [e6bfa898] severe  [native] 140294683088640(ThreadPoolExecutor-0_0) - [set_full_status] 'show_checks'
 Traceback (most recent call last):
   File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/plugin_state_machine.py", line 340, in _execute_next_task
     self._query_plugin()
   File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/plugin_state_machine.py", line 667, in _query_plugin
     self._plugin_run_data = self._create_plugin_run_data()
   File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/plugin_state_machine.py", line 648, in _create_plugin_run_data
     plugin_instance = plugin_class(**plugin_args))
   File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/api/base_plugin.py", line 579, in __init__
     super().__init__(**kwargs)
   File "/opt/dynatrace/remotepluginmodule/agent/plugin/engine.zip/ruxit/api/base_plugin.py", line 418, in __init__
     self.initialize(**kwargs)
   File "/opt/dynatrace/remotepluginmodule/plugin_deployment/custom.remote.python.ssl_events/activegate_plugin_certs.py", line 32, in initialize
     self.show_checks = config["show_checks"]
   File "/opt/dynatrace/remotepluginmodule/agent/plugin/python3.6/collections/__init__.py", line 991, in __getitem__
     raise KeyError(key)
 KeyError: 'show_checks'
 ```

**Comment by bobmacks** [comment]
Downgrading to v1.016 and the issue wen't away... I suspect this error had to do with new `show_checks` functionality introduced in v1.017

**Comment by avdveen** [comment]
@bobmacks I had the same error with version 1.018 initially.
Work-around is to untick the 'Show checks' box, save the config, then re-tick the checkbox and save config again.
Error goes away and it works as expected.

**Comment by leonvzGit** [comment]
Thanks for reporting this issue @bobmacks
